name: Flujo de Inferencia IA (IA-2)

on:
  # 1. Trigger Manual: Para ejecutarlo cuando quieras desde la pestaña "Actions"
  workflow_dispatch:

  # 2. Trigger Programado: Se ejecuta diariamente a las 7:00 AM UTC
  schedule:
    - cron: '0 7 * * *'

# Establece la zona horaria para todo el flujo
env:
  TZ: 'America/Santiago'

jobs:
  run-inference:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 
      pull-requests: write

    steps:
      # --- 1. CONFIGURACIÓN INICIAL ---

      - name: 1. Checkout del Repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: 2. Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip' 

      # --- 2. OBTENCIÓN DE MODELOS ---

      - name: 3. Crear Directorio de Modelos
        run: mkdir -p models

      # --- PASO CORREGIDO ---
      - name: 4. Descargar Modelos desde Release (AI-2)
        uses: robinraju/release-downloader@v1.8
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'AI-2'
          # out-file-path es el parámetro correcto para esta versión
          out-file-path: 'models/' 

      - name: 5. Verificar Modelos Descargados (Opcional)
        run: |
          echo "Contenido del directorio de modelos:"
          ls -l models/

      # --- 3. EJECUCIÓN DEL PIPELINE ---

      - name: 6. Instalar Dependencias de IA
        run: |
          pip install -r requirements.txt

      - name: 7. Ejecutar Pipeline de Inferencia
        run: |
          python -m src.main --horizonte 120

      # --- 4. PUBLICACIÓN DE RESULTADOS ---

      - name: 8. Publicar Salidas JSON (Commit al Repo)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'CI: Actualización automática de predicciones IA'
          file_pattern: 'public/Predicion_daria.json public/prediccion_horaria.json public/alertas_climaticas.json'
          commit_user_name: 'IA Prediction Bot'
          commit_user_email: 'actions@github.com'
          commit_author: 'IA Prediction Bot <actions@github.com>'
